"""
Configuración y constantes del juego
"""
import pygame

# --- Configuración de la ventana ---
ANCHO = 800
ALTO = 600

# --- Definición de colores ---
BLANCO = (255, 255, 255)
NEGRO = (0, 0, 0)
ROJO = (255, 0, 0)
VERDE = (0, 255, 0)
AZUL = (0, 0, 255)

# --- Configuración del juego (Constantes) ---
VELOCIDAD_NAVE = 7
VELOCIDAD_LASER = 10
VELOCIDAD_ENEMIGO_BASE = 2
VELOCIDAD_FONDO = 2
VELOCIDAD_POWERUP = 1

# Constantes del jefe
NIVEL_APARICION_JEFE = 10
VIDAS_JEFE_BASE = 300
VELOCIDAD_INICIAL_JEFE = 1.5
ALTURA_PARADA_JEFE = 120

# Movimiento del jefe
AMPLITUD_OSCILACION_JEFE_X = 150
FRECUENCIA_OSCILACION_JEFE_X = 0.002

# Constantes de Disparos del Jefe
TIEMPO_DISPARO_JEFE_NORMAL = 2000
VELOCIDAD_BALA_JEFE = 6
DAÑO_BALA_JEFE = 1

# Constantes de Misiles/Bombas del Jefe
TIEMPO_LANZAMIENTO_MISIL_JEFE = 3000
VELOCIDAD_MISIL_JEFE = 4
DAÑO_MISIL_JEFE = 2
VELOCIDAD_ANIMACION_PROYECTIL_JEFE = 100

# Constantes de Bala Perseguidor del Jefe
TIEMPO_DISPARO_BALA_PERSEGUIDORA_JEFE = 4000
VELOCIDAD_BALA_PERSEGUIDORA = 3
DAÑO_BALA_PERSEGUIDORA = 1
GIRO_BALA_PERSEGUIDORA = 0.03

# Constantes de Invocación de Enemigos por el Jefe
TIEMPO_INVOCACION_JEFE = 8000
ENEMIGOS_POR_OLEADA_JEFE_INVOCADOS = 3

# Power-ups
TIEMPO_ENTRE_POWERUPS = 8000
DURACION_POWERUP_EN_PANTALLA = 2500
DURACION_POWERUP_VELOCIDAD = 5000
DURACION_POWERUP_ESCUDO = 8000

# Enemigos
TIEMPO_DISPARO_ENEMIGO = 1500
VELOCIDAD_LASER_ENEMIGO = 4

# Variables globales
puntaje = 0
high_score = 0